# This file builds two versions of the QA report:
# 1. A clean HTML report saved locally for your portfolio
# 2. A markdown report for posting as a GitHub PR comment
# Having both formats means the report works everywhere.

from config import GITHUB_REPO


# Colour mapping for risk levels.
RISK_COLORS = {
    "LOW": "#22c55e",
    "MEDIUM": "#f59e0b",
    "HIGH": "#ef4444"
}


def generate_html_report(pr_details, test_cases, risk_analysis):
    # Build a professional HTML report from all the AI analysis results.
    # This is the visual report that opens in the browser.

    risk_level = risk_analysis.get("risk_level", "UNKNOWN")
    risk_color = RISK_COLORS.get(risk_level, "#6b7280")
    quality_score = risk_analysis.get("quality_score", "N/A")

    html = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>AI QA Copilot Report - PR #{pr_details['number']}</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px;
                background: #f8f9fa; color: #333; }}
        h1 {{ color: #1e293b; border-bottom: 3px solid #6366f1;
              padding-bottom: 10px; }}
        h2 {{ color: #1e293b; margin-top: 40px; }}
        h3 {{ color: #475569; }}
        .summary-cards {{ display: flex; gap: 20px; margin: 30px 0;
                          flex-wrap: wrap; }}
        .card {{ background: white; padding: 20px 30px; border-radius: 10px;
                 box-shadow: 0 1px 4px rgba(0,0,0,0.1); text-align: center; }}
        .card h2 {{ font-size: 32px; margin: 0; color: #6366f1; }}
        .card p {{ margin: 5px 0 0; color: #64748b; font-size: 14px; }}
        .badge {{ padding: 6px 16px; border-radius: 20px; color: white;
                  font-weight: bold; font-size: 14px; display: inline-block; }}
        .section {{ background: white; border-radius: 10px; padding: 25px;
                    margin: 20px 0; box-shadow: 0 1px 4px rgba(0,0,0,0.1); }}
        .pr-meta {{ display: grid; grid-template-columns: 1fr 1fr;
                    gap: 12px; margin-top: 15px; }}
        .meta-item {{ background: #f1f5f9; padding: 10px 14px;
                      border-radius: 6px; font-size: 14px; }}
        .meta-item strong {{ color: #1e293b; }}
        .risk-reason {{ background: #fef9c3; border-left: 4px solid #f59e0b;
                        padding: 8px 12px; margin: 6px 0; border-radius: 4px;
                        font-size: 14px; }}
        .test-cases {{ background: #f8fafc; border-radius: 8px; padding: 20px;
                       white-space: pre-wrap; font-size: 14px;
                       border: 1px solid #e2e8f0; line-height: 1.6; }}
        .info-item {{ background: #eff6ff; border-left: 4px solid #6366f1;
                      padding: 10px 14px; margin: 8px 0; border-radius: 4px;
                      font-size: 14px; }}
        a {{ color: #6366f1; }}
    </style>
</head>
<body>
    <h1>AI QA Copilot Report</h1>
    <p>Auto-generated by AI QA Copilot | Powered by LLaMA 3.3 via Groq</p>

    <div class="summary-cards">
        <div class="card">
            <h2>{pr_details['changed_files']}</h2>
            <p>Files Changed</p>
        </div>
        <div class="card">
            <h2 style="color:#22c55e">+{pr_details['additions']}</h2>
            <p>Lines Added</p>
        </div>
        <div class="card">
            <h2 style="color:#ef4444">-{pr_details['deletions']}</h2>
            <p>Lines Removed</p>
        </div>
        <div class="card">
            <h2 style="color:{risk_color}">{risk_level}</h2>
            <p>Risk Level</p>
        </div>
        <div class="card">
            <h2>{quality_score}/10</h2>
            <p>Quality Score</p>
        </div>
    </div>

    <div class="section">
        <h2>Pull Request Details</h2>
        <h3>
            <a href="{pr_details['url']}" target="_blank">
                PR #{pr_details['number']}: {pr_details['title']}
            </a>
        </h3>
        <div class="pr-meta">
            <div class="meta-item"><strong>Author:</strong> {pr_details['author']}</div>
            <div class="meta-item"><strong>Base Branch:</strong> {pr_details['base_branch']}</div>
            <div class="meta-item"><strong>Head Branch:</strong> {pr_details['head_branch']}</div>
            <div class="meta-item"><strong>Created:</strong> {pr_details['created_at']}</div>
        </div>
        <p style="margin-top:15px; color:#475569;">{pr_details['body']}</p>
    </div>

    <div class="section">
        <h2>Risk Assessment</h2>
        <p>
            <span class="badge" style="background:{risk_color}">
                {risk_level} RISK
            </span>
        </p>
        <p style="margin-top:15px; color:#475569;">
            {risk_analysis.get('summary', '')}
        </p>

        <h3>Risk Reasons</h3>
        {"".join(f'<div class="risk-reason">{r}</div>'
            for r in risk_analysis.get('risk_reasons', []))}

        <h3>Testing Types Needed</h3>
        <div class="info-item">
            {risk_analysis.get('testing_types', 'Not provided')}
        </div>

        <h3>Critical Areas to Focus On</h3>
        <div class="info-item">
            {risk_analysis.get('critical_areas', 'Not provided')}
        </div>
    </div>

    <div class="section">
        <h2>Generated Test Cases</h2>
        <p style="color:#475569; margin-bottom:15px;">
            AI generated test cases based on the actual code changes in this PR.
        </p>
        <div class="test-cases">{test_cases}</div>
    </div>

</body>
</html>
"""

    return html


def generate_pr_comment(pr_details, test_cases, risk_analysis):
    # Build a markdown formatted comment to post directly on the GitHub PR.
    # GitHub renders markdown beautifully in PR comments.
    # This is what the developer sees when they open their PR.

    risk_level = risk_analysis.get("risk_level", "UNKNOWN")
    quality_score = risk_analysis.get("quality_score", "N/A")

    # Choose an emoji based on risk level for visual clarity.
    risk_emoji = {"LOW": "🟢", "MEDIUM": "🟡", "HIGH": "🔴"}.get(risk_level, "⚪")

    # We define newline as a variable because you cannot use
    # escape sequences like \n directly inside f-strings in Python.
    newline = "\n"

    # Build risk reasons as a separate variable outside the f-string
    # to avoid the nested f-string syntax error.
    risk_reasons_text = newline.join(
        f"- {r}" for r in risk_analysis.get('risk_reasons', [])
    )

    comment = f"""## 🤖 AI QA Copilot Report

> Auto-generated quality assessment for PR #{pr_details['number']}

---

### Summary
| Metric | Value |
|--------|-------|
| Risk Level | {risk_emoji} {risk_level} |
| Quality Score | {quality_score}/10 |
| Files Changed | {pr_details['changed_files']} |
| Lines Added | +{pr_details['additions']} |
| Lines Removed | -{pr_details['deletions']} |

---

### Risk Assessment
{risk_analysis.get('summary', '')}

**Risk Reasons:**
{risk_reasons_text}

**Testing Types Needed:** {risk_analysis.get('testing_types', 'N/A')}

**Critical Areas:** {risk_analysis.get('critical_areas', 'N/A')}

---

### Generated Test Cases
{test_cases}
---
*Generated by AI QA Copilot | Powered by LLaMA 3.3 70B via Groq*
"""

    return comment